export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  TRIP_NOT_FOUND: 'TRIP_NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_TRIP_OWNER: 'NOT_TRIP_OWNER',
  TRIP_BUDGET_NOT_SET: 'TRIP_BUDGET_NOT_SET',
  BUDGET_SUM_EXCEEDED: 'BUDGET_SUM_EXCEEDED',
  QUOTA_BELOW_USED: 'QUOTA_BELOW_USED',
  EXPENSE_EXCEEDS_CATEGORY: 'EXPENSE_EXCEEDS_CATEGORY',
  TRANSFER_EXCEEDS_REMAINING: 'TRANSFER_EXCEEDS_REMAINING',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;
