export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  TRIP_NOT_FOUND: 'TRIP_NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_TRIP_OWNER: 'NOT_TRIP_OWNER',
  BUDGET_NOT_INITIALIZED: 'BUDGET_NOT_INITIALIZED',
  BUDGET_CATEGORY_INVALID: 'BUDGET_CATEGORY_INVALID',
  BUDGET_AMOUNT_INVALID: 'BUDGET_AMOUNT_INVALID',
  BUDGET_REQUEST_ID_REQUIRED: 'BUDGET_REQUEST_ID_REQUIRED',
  BUDGET_REQUEST_CONFLICT: 'BUDGET_REQUEST_CONFLICT',
  BUDGET_TOTAL_EXCEEDED: 'BUDGET_TOTAL_EXCEEDED',
  BUDGET_QUOTA_EXCEEDED: 'BUDGET_QUOTA_EXCEEDED',
  BUDGET_TRANSFER_INVALID: 'BUDGET_TRANSFER_INVALID',
  BUDGET_TRANSFER_EXCEEDED: 'BUDGET_TRANSFER_EXCEEDED',
  BUDGET_PLANNED_BELOW_SPENT: 'BUDGET_PLANNED_BELOW_SPENT'
} as const;
